"""Generate the portable, static portfolio. Run with Python 3; no dependencies."""
from pathlib import Path
from html import escape
from experience import enhance

OUT=Path(__file__).parent/'dist'
ICON="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='8' fill='%230a1624'/%3E%3Cpath d='M10 29V11h20M10 20h14' fill='none' stroke='%2391e4d3' stroke-width='4'/%3E%3C/svg%3E"
LINKEDIN='https://www.linkedin.com/in/florian-marchois-170103328/'
EMAIL='marchois.florian@gmail.com'

def page(file,title,desc,body,active='',scripts=''):
 nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if active==label else '')+f'>{label}</a>' for label,url in [('Projets','index.html#projets'),('Parcours','parcours.html'),('Air France','air-france.html'),('Compétences','competences.html')])
 html=f'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#091420"><title>{escape(title)} — Florian Marchois</title><meta name="description" content="{escape(desc)}"><meta property="og:title" content="{escape(title)} — Florian Marchois"><meta property="og:description" content="{escape(desc)}"><meta property="og:type" content="website"><link rel="icon" href="{ICON}"><link rel="stylesheet" href="assets/style.css"><script src="assets/site.js" defer></script>{scripts}</head><body><a class="skip" href="#main">Aller au contenu</a><div class="reading-progress" aria-hidden="true"></div><header class="header"><a class="brand" href="index.html" aria-label="Florian Marchois, accueil">fm<span>Florian Marchois</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span>＋</span></button><nav id="navigation" aria-label="Navigation principale">{nav}<a class="nav-contact" href="contact.html" {'aria-current="page"' if active=='Contact' else ''}>Échangeons ↗</a></nav></header><main id="main">{body}</main><footer><a href="index.html">Florian Marchois <span class="footer-sub">Élève ingénieur · Arts et Métiers</span></a><div><a href="contact.html">Contact</a><a href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="assets/florian-marchois-cv.pdf" download>CV ↓</a></div><span class="copyright">© 2026</span></footer></body></html>'''
 html=html.replace('<script src="assets/site.js"', '<link rel="stylesheet" href="assets/pages.css"><script src="assets/site.js"')
 for material in ['aluminium','bois']:
  html=html.replace(f'src="assets/mode-{material}.gif"',f'src="assets/mode-{material}.jpg" data-animation="assets/mode-{material}.gif" data-still="assets/mode-{material}.jpg"')
  html=html.replace(f'<audio controls preload="none" src="assets/gamme-{material}.wav"',f'<button class="motion-button" data-motion="mode-{material}" aria-pressed="false">Animer la déformée</button><audio controls preload="none" src="assets/gamme-{material}.wav"')
 html=enhance(file,html)
 (OUT/file).write_text(html,encoding='utf-8')

def tags(*items):return '<div class="tags">'+''.join(f'<span>{i}</span>' for i in items)+'</div>'
def stats(items):return '<div class="metrics">'+''.join(f'<div><strong>{n}</strong><span>{label}</span></div>' for n,label in items)+'</div>'
def note(text):return f'<p class="source-note">{text}</p>'
def next_project(href,name,domain):return f'<a class="next-project" href="{href}"><span class="eyebrow">POURSUIVRE L’EXPLORATION</span><strong>{name} <span>↗</span></strong><p>{domain}</p></a>'
def hero(num,domain,title,lead,meta):return f'<section class="project-hero wrap"><a class="back-link" href="index.html#projets">← Tous les projets</a><p class="eyebrow">{num} / {domain}</p><h1>{title}</h1><p class="project-lead">{lead}</p><div class="project-meta">{meta}</div></section>'
def section(id,kicker,title,body):return f'<section id="{id}" class="section project-section"><div class="section-aside"><p class="eyebrow">{kicker}</p><h2>{title}</h2></div><div class="section-body">{body}</div></section>'

home='''<section class="hero"><div class="hero-copy"><p class="eyebrow">ÉLÈVE INGÉNIEUR · ARTS ET MÉTIERS</p><h1>Comprendre.<br>Modéliser.<br><em>Faire avancer.</em></h1><p class="intro">Je suis Florian Marchois. De la vibration d’une lame à l’organisation d’un atelier, je relie l’analyse scientifique aux décisions industrielles.</p><a class="button" href="#projets">Explorer mes projets <span>↓</span></a><div class="hero-meta"><span>Simulation & mécanique</span><span>Supply Chain</span><span>Data</span></div></div><div class="hero-visual"><div class="visual-top"><p class="eyebrow">LE COMPOSITEAUPHONE</p><span class="small-label">SIGNAL / 01</span></div><div class="wave-display"><canvas id="signal" width="800" height="400" role="img" aria-label="Signal sonore de synthèse d’une lame métallique à 440 hertz"></canvas><span class="axis-label">TEMPS →</span></div><div class="hero-readout"><span>UN MODÈLE QUI S’ÉCOUTE.</span><strong>440 <small>Hz</small></strong><p>La de référence · synthèse d’une lame métallique</p></div><audio id="hero-audio" src="assets/la440.wav" preload="none"></audio><button class="sound-button" data-audio="hero-audio" aria-pressed="false"><span class="play-icon">▷</span> Écouter la lame</button><a class="visual-project" href="compositeauphone.html" aria-label="Découvrir le Compositeauphone">↗</a></div></section>
<div class="intro-band wrap"><span>DE LA PHYSIQUE<br>À L’INGÉNIERIE</span><p>Modéliser pour comprendre. Comparer pour décider.<br>Expérimenter pour confronter les idées au réel.</p><a href="parcours.html" class="text-link">Mon parcours ↗</a></div>
<section id="projets" class="section"><div class="section-heading split-heading"><div><p class="eyebrow">TRAVAUX SÉLECTIONNÉS / 2025–2026</p><h2>Quatre projets.<br>Plusieurs façons de résoudre.</h2></div><p>Des projets collectifs aux Arts et Métiers.<br>Des méthodes, des choix et des résultats.</p></div><div class="project-grid">
<a class="project-card featured" href="compositeauphone.html"><div class="card-visual photo"><img src="assets/fabrication.jpg" alt="Drapage d’une lame composite dans son moule" width="600" height="500" loading="lazy"><div class="visual-caption">DU MODÈLE AU PROTOTYPE</div><span class="card-number">01</span></div><div class="card-copy"><span class="eyebrow">MÉCANIQUE · PYTHON · ABAQUS</span><h3>Compositeauphone</h3><p>Concevoir une lame composite et trouver la note juste.</p><span class="card-bottom"><span>1 024 empilements explorés</span><span class="round-arrow">↗</span></span></div></a>
<a class="project-card" href="chanel.html"><div class="card-visual mini-flow"><span class="card-number">02</span><div class="flow-preview"><b>Production</b><i>→</i><b>Hubs</b><i>→</i><b>Boutiques</b></div><span class="visual-caption">MATIÈRE ↔ INFORMATION</span></div><div class="card-copy"><span class="eyebrow">SUPPLY CHAIN · STOCKS</span><h3>Chanel</h3><p>Repenser les stocks et les tailles de lots de maquillage.</p><span class="card-bottom"><span>Production & distribution</span><span class="round-arrow">↗</span></span></div></a>
<a class="project-card" href="boscha.html"><div class="card-visual mini-capacity"><span class="card-number">03</span><div class="capacity-preview"><span>Charge <i></i></span><span>Capacité <i></i></span></div><span class="visual-caption">IDENTIFIER LE GOULOT</span></div><div class="card-copy"><span class="eyebrow">ORGANISATION · PERFORMANCE INDUSTRIELLE</span><h3>Boscha</h3><p>Comprendre les retards et réorganiser les flux d’un atelier.</p><span class="card-bottom"><span>Diagnostic & scénarios</span><span class="round-arrow">↗</span></span></div></a>
<a class="project-card" href="data.html"><div class="card-visual mini-data"><span class="card-number">04</span><div class="big-number">199<span>bobines étudiées</span></div><span class="visual-caption">DE LA MESURE À LA DÉCISION</span></div><div class="card-copy"><span class="eyebrow">DATA · STATISTIQUES · QUALITÉ</span><h3>Expliquer la variabilité</h3><p>Identifier les paramètres qui comptent dans la fabrication.</p><span class="card-bottom"><span>Python & régression</span><span class="round-arrow">↗</span></span></div></a>
</div></section>
<section class="section air-teaser"><div><p class="eyebrow">L’EXPÉRIENCE HUMAINE</p><h2>Deux saisons.<br>Au sein des équipages.</h2></div><div><p>Personnel Complémentaire de Bord chez Air France : une autre dimension de mon parcours, au contact des passagers et des équipes.</p><a class="text-link" href="air-france.html">Découvrir mon expérience Air France ↗</a></div></section>
<section class="section contact-banner"><p class="eyebrow">ET LA SUITE ?</p><h2>Parlons de vos<br><em>problèmes à résoudre.</em></h2><a class="button" href="contact.html">Entrer en contact <span>↗</span></a></section>'''
page('index.html','Ingénierie & performance industrielle','Florian Marchois, élève ingénieur Arts et Métiers. Découvrez ses projets de simulation, Supply Chain, organisation industrielle et Data.',home,scripts='<script src="assets/signal.js" defer></script>')

cosa=hero('01','MÉCANIQUE & SIMULATION','De la matière<br><em>à la note juste.</em>','Le Compositeauphone : concevoir, fabriquer et accorder une lame de xylophone en matériaux composites.','<span>Arts et Métiers · 2A · 2025–2026</span><span>Projet collectif · 4 étudiants</span>')
cosa+='<div class="wrap">'+stats([('1 024','empilements étudiés par le modèle Python'),('20','plis dans le stratifié étudié'),('1 322,9 Hz','fréquence finale mesurée au microphone')])+'</div>'
cosa+='<nav class="chapter-nav wrap" aria-label="Dans ce projet"><a href="#enjeu">L’enjeu</a><a href="#approche">La démarche</a><a href="#experience">Écouter & explorer</a><a href="#resultats">Les résultats</a></nav>'
cosa+=section('enjeu','01 / LE DÉFI','Une lame doit<br>sonner juste.','<p class="large-copy">Changer de matériau transforme la vibration. Comment obtenir la note voulue avec une lame composite, alors que l’orientation des fibres et la fabrication influencent sa rigidité ?</p><p>Nous sommes partis des lames en bois et en aluminium pour relier géométrie, matériaux et fréquences propres. Puis nous avons transféré cette démarche à un stratifié composite, jusqu’à la fabrication et à la mesure de la pièce.</p>'+tags('Analyse modale','Éléments finis','Matériaux composites','Travail en équipe'))
cosa+=section('approche','02 / LA DÉMARCHE','Calculer vite.<br>Vérifier au réel.','''<div class="steps"><article><span>01</span><div><h3>Comprendre la vibration</h3><p>Modèles de poutre, amortissement et synthèse sonore sous Python. Les essais permettent d’identifier les modes de flexion et de torsion.</p></div></article><article><span>02</span><div><h3>Explorer les empilements</h3><p>Un modèle analytique couplé à la théorie des stratifiés explore 1 024 configurations symétriques à 20 plis. Abaqus sert ensuite à vérifier les configurations retenues.</p></div></article><article><span>03</span><div><h3>Fabriquer et contrôler</h3><p>Drapage, mise sous vide, cuisson et découpe. Un contrôle ultrasonore examine la qualité du stratifié avant la caractérisation vibratoire.</p></div></article><article><span>04</span><div><h3>Corriger la pièce</h3><p>La première fréquence mesurée est trop basse. Le retrait de matière aux extrémités permet de remonter la fréquence, avec un dimensionnement numérique puis une nouvelle mesure.</p></div></article></div>''')
cosa+='''<section class="section gallery-section"><div class="photo-pair"><figure><img src="assets/fabrication.jpg" alt="Moule contenant les plis du composite" width="600" height="800" loading="lazy"><figcaption>01 — Drapage dans le moule.</figcaption></figure><figure><img src="assets/mise-sous-vide.jpg" alt="Moule sous une poche à vide" width="600" height="800" loading="lazy"><figcaption>02 — Mise sous vide du stratifié.</figcaption></figure><figure><img src="assets/lame-usinee.jpg" alt="Lame composite avec évidements d’accordage aux deux extrémités" width="600" height="800" loading="lazy"><figcaption>03 — La lame après usinage d’accordage.</figcaption></figure></div>'''+note('Photographies extraites du rapport collectif COSA, pages 29 et 41.')+'</section>'
cosa+=section('experience','03 / EXPLORER','Un matériau.<br>Un autre timbre.','''<p>Ces gammes sont des sons de synthèse issus du projet. Elles rendent audible l’effet du modèle de lame et de son amortissement. Ce ne sont pas des enregistrements du prototype composite.</p><div class="audio-grid"><div class="audio-card"><h3>Aluminium</h3><img src="assets/mode-aluminium.gif" alt="Animation de la déformation d’une lame métallique" width="640" height="480" loading="lazy"><audio controls preload="none" src="assets/gamme-aluminium.wav" aria-label="Écouter la gamme synthétique aluminium"></audio></div><div class="audio-card"><h3>Bois</h3><img src="assets/mode-bois.gif" alt="Animation de la déformation d’une lame en bois" width="640" height="480" loading="lazy"><audio controls preload="none" src="assets/gamme-bois.wav" aria-label="Écouter la gamme synthétique bois"></audio></div></div><div class="engineering-note"><h3>Le compromis du modèle</h3><p>Le modèle analytique accélère l’exploration. Certaines orientations de fibres et les modes supérieurs exigent cependant une modélisation plus complète. L’intérêt est de savoir quand passer du calcul rapide aux éléments finis.</p></div>''')
cosa+=section('resultats','04 / DU CALCUL À LA MESURE','Accorder.<br>Puis mesurer.','''<div class="tuning-chart" role="img" aria-label="Avant accordage : 1226 hertz. Cible : 1318,5 hertz. Après accordage, mesure au microphone : 1322,9 hertz."><div><span>Avant accordage</span><b>1 226 Hz</b><i style="--bar:54%"></i></div><div><span>Cible Mi6 du projet</span><b>1 318,5 Hz</b><i style="--bar:96%"></i></div><div class="highlight"><span>Après accordage · microphone</span><b>1 322,9 Hz</b><i style="--bar:98%"></i></div><small>Échelle comparative : 1 100–1 330 Hz.</small></div><p>La mesure finale au microphone se situe à environ <strong>5,7 cents</strong> de la cible, soit un écart de fréquence de 0,33 %. Une mesure par accéléromètre donne une valeur légèrement plus basse : la masse du capteur influence elle-même la vibration.</p><details><summary>Voir la mesure expérimentale</summary><figure class="document-figure"><img src="assets/mesure-finale.jpg" alt="Spectre expérimental du microphone et pic de fréquence de la lame" loading="lazy"><figcaption>Extrait du rapport COSA, page 43.</figcaption></figure></details>'''+note('Résultats collectifs du rapport COSA, pages 42–44. La note « Mi6 » reprend la convention utilisée dans le projet.'))
cosa+=section('recul','05 / CE QUE J’EN RETIENS','Le modèle guide.<br>L’essai tranche.','<p class="large-copy">Une bonne prédiction ne suffit pas : la fabrication et la mesure ont leurs propres effets.</p><p>Ce projet relie programmation, mécanique, choix de matériaux et expérimentation. Il montre aussi pourquoi il faut garder une marge pour le recalage : épaisseur réelle, hétérogénéité du stratifié et conditions de mesure peuvent déplacer la fréquence.</p><p class="contribution">J’ai participé à ce projet avec trois autres étudiants. Les méthodes et résultats présentés sont ceux de notre travail collectif.</p>'+tags('Python','Abaqus','Analyse vibratoire','Confrontation modèle / expérience'))
cosa+=next_project('chanel.html','Chanel','Passer du comportement d’une lame à celui d’un réseau de distribution.')
page('compositeauphone.html','Compositeauphone','Conception et accordage d’une lame composite : Python, Abaqus, fabrication et analyse vibratoire expérimentale.',cosa,'Projets')

chanel=hero('02','SUPPLY CHAIN','Le bon stock.<br><em>Au bon endroit.</em>','Étudier l’organisation des stocks et les tailles de lots de produits de maquillage Chanel, de la production aux boutiques.','<span>Arts et Métiers · Projet académique collectif</span><span>Stocks · Flux · Distribution</span>')
chanel+=section('enjeu','01 / LE PROBLÈME','Relier production<br>et demande.','<p class="large-copy">Réduire les surstocks tout en gardant les produits disponibles : la question engage toute la chaîne de distribution.</p><p>Le projet étudie ensemble les tailles de lots, les stocks en boutique et la remontée d’information vers la production. La segmentation des produits conduit à proposer des réponses différentes selon leur profil.</p>'+tags('Gestion des stocks','Tailles de lots','Segmentation ABC','Analyse de scénarios'))
chanel+='''<section class="section wide-panel"><div class="panel-heading"><p class="eyebrow">EXPLORER LA LOGIQUE DES FLUX</p><h2>Où se situe le stock ?</h2><p>Deux organisations schématiques pour comprendre les pistes du projet.</p></div><div class="segmented" role="group" aria-label="Organisation des flux"><button data-flow="initial" aria-pressed="true">Organisation étudiée</button><button data-flow="proposed" aria-pressed="false">Piste proposée</button></div><div class="flow-diagram" id="flow-diagram"><div class="flow-node"><span>01</span><strong>Production</strong><small>Usine en France</small></div><div class="flow-line" aria-hidden="true">→</div><div class="flow-node middle-node"><span>02</span><strong id="flow-middle">Entrepôt central</strong><small id="flow-mid-caption">Distribution vers les boutiques</small></div><div class="flow-line" aria-hidden="true">→</div><div class="flow-node"><span>03</span><strong>Boutiques</strong><small id="flow-last-caption">Stock local important</small></div></div><p id="flow-description" class="flow-description" aria-live="polite">Dans l’organisation étudiée, le stock est réparti dans les boutiques. Le projet questionne sa localisation et la manière de déclencher les réapprovisionnements.</p>'''+note('Schéma explicatif redessiné à partir de la présentation Chanel. Il représente une logique de distribution, pas une simulation chiffrée.')+'</section>'
chanel+=section('approche','02 / LES PISTES','Adapter la réponse<br>au produit.','''<div class="decision-list"><article><span>C</span><div><h3>Mutualiser et mieux informer</h3><p>La piste étudiée consiste à utiliser des entrepôts relais et à faire remonter les besoins pour déclencher le réapprovisionnement. Le but est de limiter l’accumulation dans chaque boutique.</p></div></article><article><span>B</span><div><h3>Rapprocher les flux du marché</h3><p>Pour un autre segment, l’équipe explore une organisation par hubs régionaux et compare ses implications logistiques et économiques.</p></div></article><article><span>↔</span><div><h3>Revenir à la production</h3><p>Le travail inclut des pistes sur l’organisation des lignes et les tailles de lots. La distribution ne peut être optimisée indépendamment de l’atelier.</p></div></article></div>''')
chanel+=section('resultats','03 / LE LIVRABLE','Des scénarios<br>pour décider.','<p>Une présentation structurée rassemble le diagnostic, les schémas de flux avant/après et les recommandations. Elle inclut également une démonstration numérique pour rendre la proposition plus lisible.</p><p class="engineering-note">Les solutions sont des propositions issues du projet académique. Elles ne sont pas présentées comme un déploiement réalisé chez Chanel, ni comme des gains effectivement mesurés.</p>'+tags('Diagnostic','Comparaison d’organisations','Restitution visuelle','Recommandations'))
chanel+=section('recul','04 / CE QUE J’EN RETIENS','Regarder<br>toute la chaîne.','<p class="large-copy">Une décision sur la taille d’un lot déplace aussi des stocks, des délais et des besoins d’information.</p><p>Ce travail m’a amené à relier plusieurs niveaux de décision et à expliciter les hypothèses d’un scénario. L’enjeu est de proposer une organisation compréhensible, dont les effets peuvent ensuite être évalués.</p><p class="contribution">Participation à un travail collectif aux Arts et Métiers. Synthèse fondée sur la présentation du projet.</p>')
chanel+=next_project('boscha.html','Boscha','Analyser les capacités et les flux à l’échelle de l’atelier.')
page('chanel.html','Chanel · Stocks & Supply Chain','Projet académique Chanel : stocks, tailles de lots et comparaison de scénarios de distribution.',chanel,'Projets')

boscha=hero('03','PERFORMANCE INDUSTRIELLE','Comprendre les retards.<br><em>Repenser l’atelier.</em>','Boscha : une étude de cas qui relie charge des machines, circulation des pièces et choix d’investissement.','<span>Arts et Métiers · OREXA</span><span>Étude de cas collective · Organisation de production</span>')
boscha+=section('enjeu','01 / LE DIAGNOSTIC','La capacité globale<br>ne dit pas tout.','<p class="large-copy">Un atelier peut disposer de ressources tout en accumulant des retards sur un poste critique.</p><p>Le cas Boscha porte sur une gamme d’injecteurs. Nous avons étudié les gammes de fabrication, la charge des postes et les règles de lancement pour comprendre ce qui limite réellement le débit.</p>'+tags('Charge / capacité','Goulots','Gammes de fabrication','Gestion des flux'))
boscha+=section('methode','02 / LA MÉTHODE','Du poste machine<br>au plan d’atelier.','''<div class="steps"><article><span>01</span><div><h3>Comparer charge et capacité</h3><p>Ramener les besoins et les ressources au même horizon pour identifier les postes saturés et les marges disponibles.</p></div></article><article><span>02</span><div><h3>Cartographier les déplacements</h3><p>Construire une matrice de flux entre les opérations, les stockages et les étapes de sous-traitance.</p></div></article><article><span>03</span><div><h3>Adapter l’implantation</h3><p>Utiliser une proposition algorithmique comme point de départ, puis la retravailler pour intégrer les circulations et la forme réelle des postes.</p></div></article></div>''')
boscha+='''<section class="section layout-section"><div class="section-heading"><p class="eyebrow">LE PASSAGE AU CONCRET</p><h2>Un plan doit aussi<br>laisser passer les personnes.</h2><p>L’implantation proposée intègre des zones de circulation entre les postes.</p></div><figure class="document-figure"><img src="assets/implantation-boscha.jpg" alt="Plan d’implantation de l’atelier Boscha, avec postes colorés et voies de circulation" width="1280" height="720" loading="lazy"><figcaption>Extrait du support collectif COSYP — implantation avec circulations.</figcaption></figure></section>'''
boscha+=section('scenarios','03 / ARBITRER','Trois leviers.<br>Des compromis.','''<div class="scenario-cards"><article><span class="eyebrow">SCÉNARIO A</span><h3>Étendre les horaires</h3><p>Ajouter de la capacité par une équipe de fin de semaine.</p><span class="tradeoff">À examiner : coûts récurrents et contrainte sociale.</span></article><article><span class="eyebrow">SCÉNARIO B</span><h3>Ajouter une machine</h3><p>Renforcer le poste identifié comme goulot.</p><span class="tradeoff">À examiner : investissement et déplacement du goulot.</span></article><article><span class="eyebrow">SCÉNARIO C</span><h3>Développer la polyvalence</h3><p>Redistribuer la charge entre plusieurs équipements.</p><span class="tradeoff">À examiner : faisabilité des gammes et formation.</span></article></div><p>La comparaison croise effets capacitaires, coûts et contraintes d’organisation. Elle débouche sur une recommandation progressive, plutôt que sur un achat de machine considéré isolément.</p>'''+note('Options étudiées dans le rapport Boscha. Les effets attendus sont des résultats d’étude, pas des gains d’usine constatés.'))
boscha+=section('recul','04 / CE QUE J’EN RETIENS','Optimiser avec<br>les contraintes réelles.','<p class="large-copy">Une implantation mathématiquement intéressante peut devenir inutilisable si elle oublie les accès et les circulations.</p><p>Ce projet met en regard le modèle et l’usage concret de l’atelier. Il m’a appris à examiner une solution à plusieurs échelles : le poste, le flux complet, puis les moyens nécessaires à sa mise en œuvre.</p><p class="contribution">Étude collective. Présentation des méthodes et arbitrages documentés dans les livrables OREXA.</p>')
boscha+=next_project('data.html','Data & qualité','Utiliser les mesures de production pour comprendre la variabilité.')
page('boscha.html','Boscha · Organisation industrielle','Diagnostic capacitaire, matrice des flux et implantation d’atelier dans le cas Boscha.',boscha,'Projets')

data=hero('04','DATA & QUALITÉ','Des mesures.<br><em>Des décisions mieux ciblées.</em>','Modélisation statistique de bobines toriques : expliquer la variabilité de l’inductance et identifier les paramètres de fabrication à surveiller.','<span>Arts et Métiers · MINA · 2025–2026</span><span>Projet collectif · 3 étudiants</span>')
data+='<div class="wrap">'+stats([('199','bobines dans le jeu de données du projet'),('6','variables explicatives étudiées'),('2','approches confrontées : statistiques et physique')])+'</div>'
data+=section('probleme','01 / LA QUESTION','Que faut-il<br>vraiment mesurer ?','<p class="large-copy">Toutes les dimensions d’un composant varient. Toutes n’expliquent pas autant la variation de sa performance.</p><p>À partir des mesures de bobines produites en série, nous avons cherché à prédire l’inductance, puis à hiérarchiser les paramètres influents. L’objectif est de concentrer le contrôle sur les grandeurs utiles.</p>'+tags('Analyse exploratoire','Tests statistiques','Régression multiple','Python & Excel'))
data+='''<section class="section wide-panel"><div class="panel-heading"><p class="eyebrow">EXPLORER LES DONNÉES DU PROJET</p><h2>Chaque point est une bobine.</h2><p>Changez la variable pour observer sa relation avec l’inductance mesurée.</p></div><div class="segmented" role="group" aria-label="Variable du graphique"><button data-variable="e" aria-pressed="true">Entrefer</button><button data-variable="s" aria-pressed="false">Section du tore</button><button data-variable="t" aria-pressed="false">Température</button></div><div class="scatter-wrap"><svg id="scatter" viewBox="0 0 850 420" role="img" aria-labelledby="scatter-title scatter-desc"><title id="scatter-title">Inductance en fonction de l’entrefer</title><desc id="scatter-desc">Nuage de points issu du tableur de projet MINA. Une tendance décroissante relie l’entrefer et l’inductance.</desc></svg></div><p id="chart-insight" class="flow-description" aria-live="polite">L’entrefer est l’un des paramètres influents identifiés dans le rapport. Le nuage montre une tendance, que la régression multiple permet d’étudier avec les autres variables.</p>'''+note('Mesures extraites du tableur collectif MINA. Le graphique est exploratoire : une relation visuelle ne démontre pas, à elle seule, une causalité.')+'</section>'
data+=section('approche','02 / LA DÉMARCHE','Du tableau brut<br>au modèle.','''<div class="steps"><article><span>01</span><div><h3>Préparer et examiner</h3><p>Nettoyage des données et analyse des distributions. Le script Python utilise pandas, NumPy et SciPy pour examiner les variables et tester leur normalité.</p></div></article><article><span>02</span><div><h3>Construire et réduire</h3><p>La régression multiple relie les variables mesurées à l’inductance. L’étude de leur influence permet de rechercher un modèle plus ciblé.</p></div></article><article><span>03</span><div><h3>Confronter à la physique</h3><p>Comparer les relations statistiques au modèle du circuit magnétique pour comprendre pourquoi certaines dimensions jouent un rôle majeur.</p></div></article></div>''')
data+=section('resultats','03 / LE RÉSULTAT','Orienter<br>le contrôle qualité.','<p class="large-copy">L’entrefer et la section du tore ressortent comme deux leviers majeurs dans l’analyse de l’inductance.</p><p>Le rapport propose de cibler leur variabilité plutôt que de multiplier les contrôles indifférenciés. C’est une recommandation issue du modèle : aucune réduction effectivement obtenue en production n’est revendiquée ici.</p><div class="engineering-note"><h3>Ce que le modèle ne prouve pas</h3><p>Un bon ajustement aux données étudiées ne garantit pas la même performance sur une nouvelle série. La validation sur d’autres données et la vérification des hypothèses restent nécessaires avant un usage industriel.</p></div>')
data+=section('recul','04 / CE QUE J’EN RETIENS','Les données<br>et le sens physique.','<p class="large-copy">Le calcul fait apparaître une relation. La compréhension du système aide à l’interpréter.</p><p>Ce projet prolonge mon parcours en physique par une approche statistique. Il montre comment utiliser la programmation pour examiner les données, puis traduire l’analyse en une décision de contrôle.</p><p class="contribution">Travail collectif avec deux autres étudiants. Les analyses et recommandations sont celles du rapport MINA.</p>')
data+=next_project('air-france.html','Air France','Découvrir une autre facette de mon parcours : le travail au sein des équipages.')
page('data.html','Data · Statistiques & qualité','Analyse statistique de bobines toriques : données, Python, régression et confrontation à la physique.',data,'Projets',scripts='<script src="assets/data.js" defer></script>')

air='''<section class="project-hero wrap"><p class="eyebrow">EXPÉRIENCE / AIR FRANCE</p><h1>À bord,<br><em>le collectif compte.</em></h1><p class="project-lead">Deux saisons en tant que Personnel Complémentaire de Bord. Une expérience au contact des passagers, aux côtés des équipages Air France.</p><div class="project-meta"><span>Personnel Complémentaire de Bord · PCB</span><span>Deux saisons</span></div></section><div class="wrap air-statement"><span class="season-number">02</span><div><p class="eyebrow">SAISONS CHEZ AIR FRANCE</p><h2>Un environnement différent.<br>Une place dans l’équipe.</h2></div></div>'''
air+=section('experience','01 / L’EXPÉRIENCE','Le travail<br>avec les équipages.','<p class="large-copy">Mon parcours ne se limite pas aux projets d’ingénierie. J’ai également travaillé à bord chez Air France pendant deux saisons.</p><p>Cette expérience ajoute une dimension de service et de relation humaine à ma formation scientifique. Elle met le travail en équipe au premier plan, dans un environnement international.</p>')
air+=section('regard','02 / DEUX CONTEXTES','Du projet collectif<br>à l’équipage.','<p>Les projets présentés dans ce portfolio montrent ma façon d’aborder un problème technique. Mon expérience à bord permet d’aborder une autre question : la manière de trouver sa place dans une équipe et de travailler avec des interlocuteurs différents.</p><p>Je peux revenir sur ces deux saisons et sur les situations vécues à l’occasion d’un échange.</p><a class="button secondary" href="contact.html">Échanger sur mon parcours ↗</a>')
air+=next_project('parcours.html','Mon parcours','De la physique à la formation d’ingénieur aux Arts et Métiers.')
page('air-france.html','Air France · Expérience à bord','Deux saisons de Florian Marchois comme Personnel Complémentaire de Bord chez Air France.',air,'Air France')

parcours='''<section class="project-hero wrap"><p class="eyebrow">À PROPOS / PARCOURS</p><h1>Une base scientifique.<br><em>Un regard industriel.</em></h1><p class="project-lead">Je suis Florian Marchois, élève ingénieur aux Arts et Métiers à Lille. Mon parcours relie physique, simulation numérique et organisation industrielle.</p></section><section class="section project-section"><div class="section-aside"><p class="eyebrow">LES ÉTAPES</p><h2>Construire<br>les liens.</h2></div><div class="section-body timeline"><article><span>2024–2027</span><h3>Arts et Métiers · Lille</h3><p>Formation d’ingénieur. Des projets qui associent conception, expérimentation, analyse de données et gestion des flux industriels.</p></article><article><span>2025–2026</span><h3>Air France · Deux saisons PCB</h3><p>Une expérience professionnelle à bord, aux côtés des équipages et au contact des passagers.</p></article><article><span>AVRIL–MAI 2024</span><h3>Laboratoire de Physique Théorique et Modélisation</h3><p>Stage à CY Cergy Paris Université : résolution numérique de l’équation de Schrödinger, propagation de paquets d’ondes et étude de leur réflexion et transmission.</p></article><article><span>2021–2024</span><h3>CY Cergy Paris Université</h3><p>Cycle universitaire préparatoire aux grandes écoles, puis licence de physique. Mathématiques, modélisation et méthodes numériques.</p></article></div></section>'''
parcours+=section('methode','MA FAÇON D’ABORDER UN SUJET','Comprendre avant<br>de conclure.','<div class="steps"><article><span>01</span><div><h3>Poser le problème</h3><p>Identifier ce que l’on cherche à améliorer, les contraintes et les données disponibles.</p></div></article><article><span>02</span><div><h3>Rendre les hypothèses visibles</h3><p>Construire un modèle, comparer les options et repérer les limites de l’analyse.</p></div></article><article><span>03</span><div><h3>Confronter et expliquer</h3><p>Comparer aux mesures ou aux contraintes d’usage, puis présenter une conclusion compréhensible.</p></div></article></div><a class="text-link" href="index.html#projets">Voir cette démarche dans mes projets ↗</a>')
parcours+='<section class="section contact-banner"><p class="eyebrow">POUR ALLER PLUS LOIN</p><h2>Les méthodes prennent<br>sens dans les projets.</h2><a class="button" href="competences.html">Explorer mes compétences ↗</a></section>'
page('parcours.html','Parcours','Le parcours scientifique et ingénieur de Florian Marchois : physique, Arts et Métiers et Air France.',parcours,'Parcours')

skills='''<section class="project-hero wrap"><p class="eyebrow">COMPÉTENCES / EN CONTEXTE</p><h1>Des outils.<br><em>Et ce que j’en fais.</em></h1><p class="project-lead">Chaque compétence renvoie à un travail concret. Explorez les projets pour voir les méthodes employées et leurs limites.</p></section><section class="section skills-grid">'''
for title,desc,labels,link,label in [
 ('Simulation & mécanique','Relier un modèle analytique, un calcul par éléments finis et une mesure vibratoire.',['Abaqus','Analyse modale','Matériaux composites'],'compositeauphone.html','Compositeauphone'),
 ('Programmation & données','Examiner les distributions, automatiser des calculs et interpréter un modèle statistique.',['Python','NumPy · pandas · SciPy','Excel','Régression'],'data.html','Data & qualité'),
 ('Supply Chain','Étudier les stocks, les tailles de lots et la circulation de l’information dans un réseau.',['Stocks','Segmentation','Analyse de scénarios'],'chanel.html','Chanel'),
 ('Organisation industrielle','Diagnostiquer un goulot et relier capacité, gammes et implantation d’atelier.',['Charge / capacité','Matrice de flux','Implantation'],'boscha.html','Boscha'),
 ('Travail collectif & restitution','Contribuer à des projets de groupe et rendre une démarche technique lisible dans un rapport ou une soutenance.',['Rapports','Présentations','Visualisation'],'index.html#projets','Les projets'),
 ('Relation & environnement international','Une expérience de travail au sein des équipages, en complément de la formation d’ingénieur.',['Air France','Deux saisons PCB'],'air-france.html','Expérience à bord')]:
 skills+=f'<article class="skill-card"><h2>{title}</h2><p>{desc}</p>{tags(*labels)}<a class="text-link" href="{link}">Voir : {label} ↗</a></article>'
skills+='</section><section class="section language-strip"><h2>Langues</h2><p><strong>Français</strong> · <strong>Anglais</strong> B2/C1 — Linguaskill · <strong>Espagnol</strong> B1</p></section>'
page('competences.html','Compétences','Les compétences de Florian Marchois illustrées par ses projets : Python, Abaqus, Data, Supply Chain et organisation industrielle.',skills,'Compétences')

contact=f'''<section class="project-hero wrap"><p class="eyebrow">CV / CONTACT</p><h1>Une question ?<br><em>Parlons-en.</em></h1><p class="project-lead">Pour échanger sur un projet, mon parcours ou une opportunité en ingénierie et performance industrielle.</p></section><section class="section contact-grid"><a class="contact-tile" href="mailto:{EMAIL}"><span class="eyebrow">PAR E-MAIL</span><h2>{EMAIL}</h2><span class="text-link">Écrire un message ↗</span></a><a class="contact-tile" href="{LINKEDIN}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">LINKEDIN</span><h2>Restons en contact.</h2><span class="text-link">Voir mon profil ↗</span></a><a class="contact-tile cv-tile" href="assets/florian-marchois-cv.pdf" download><div><span class="eyebrow">MON PARCOURS EN UNE PAGE</span><h2>Télécharger mon CV</h2><p>Formation, expériences et projets sélectionnés.</p></div><span class="download-icon">↓</span></a></section>'''
page('contact.html','CV & Contact','Contacter Florian Marchois par e-mail ou LinkedIn et télécharger son CV.',contact,'Contact')
page('404.html','Page introuvable','Retrouvez les projets de Florian Marchois.','<section class="project-hero wrap"><p class="eyebrow">404</p><h1>Reprenons<br><em>le bon chemin.</em></h1><p>Cette page n’existe pas ou a changé d’adresse.</p><a class="button" href="index.html">Retour aux projets ↗</a></section>')
print('Generated 9 pages + 404.')
